name: Bug report
description: Report an error or incorrect result
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: What happened?
      description: What did you expect to happen, and what happened instead?
      placeholder: "When I run ... I get ..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Minimal steps / command line to reproduce the issue.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Logs / traceback
      description: Paste relevant output (redact paths if needed).
      render: shell
  - type: textarea
    attributes:
      label: Environment
      description: OS, Python version, Smilei/happi version, etc.
      placeholder: "macOS 14, Python 3.11, Smilei ..."
