name: Feature request
description: Suggest an improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: What problem are you solving?
      placeholder: "I want to ..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution
      placeholder: "Add a flag / function that ..."
